### PR TITLE
post like

### PR DESCRIPTION
**Pull request by Sahilchouhan20**

### CODE REVIEW

**Review by prinigam — CHANGES_REQUESTED** [review]
The branch has conflicts, please resolve them first and one more thing, why did you push debugger in the code(Likes controller).
debugger or byebug must not be pushed

**Comment by Sahilchouhan20** [comment]
Okay sir i will resolve conflict and fix it

**Review by prinigam — APPROVED** [review]
This looks good, but please make sure to use singluar variable name(local or instance) where you need to deal with only one record. (ex: @like or like, when dealing with one like object only)
and use plural(local or instance) when you need to deal with multiple likes objects(likes or @likes).
And this should be applied to all the variable and not just like(it was just an example)

**Comment by Sahilchouhan20** [comment]
Okay sir thanks, I will take care about this

**Pull request merged**
