### PR TITLE
Post

### PR DESCRIPTION
**Pull request by Sahilchouhan20**

### CODE REVIEW

**Review by Pri-Nigam — COMMENTED** [review]
In comments controller, why didn't you use before action to find post id, instead you're finding id in every second method you've written.
Why so?

**Comment by Sahilchouhan20** [comment]
Sir i got error on nameing convention and i did't get that error when i create comment controller, So i just try to get data on view and it get error again and again that's why i used post id but now i correct nameing convention so i will correct all these on comment controller and other part.

**Review by prinigam — APPROVED** [review]
Okay, make sure to not repeat these sily mistakes from next time

**Comment by Sahilchouhan20** [comment]
sure sir

**Pull request merged**
